In [2]:
import numpy as np
from brownian_ot.simulation import FreeDiffusionSimulation
from brownian_ot.particles.particle import Sphere


In [4]:
sphere = Sphere(a = 1e-6) 

In [5]:
sim = FreeDiffusionSimulation(sphere, 5e-5, 1e-3, 1.38e-23 * 295)

In [6]:
sim = FreeDiffusionSimulation(sphere, 1e-5, 1e-3, 1.38e-23 * 295,
                                 pos0 = np.array([-1, 0.5, -0.7]) * 1e-6,
				 orient0 = np.array([[1, 0, 0],
                                                    [0, -1, 0],
				                    [0, 0, -1]]),
			         seed = 123456789)

In [7]:
traj = sim.run(1000)

In [8]:
print(traj.shape)

(1001, 7)


In [9]:
sim.run(1000, 'my_trajectory')

array([[-9.53910751e-07,  4.06827454e-07, -6.88652133e-07, ...,
        -9.95149608e-01, -5.34387075e-02, -7.38166231e-02],
       [-9.53220558e-07,  4.07128575e-07, -6.84420239e-07, ...,
        -9.95142694e-01, -5.37752531e-02, -7.42682367e-02],
       [-9.51495541e-07,  4.08998375e-07, -6.85942622e-07, ...,
        -9.95032975e-01, -5.55650306e-02, -7.42236972e-02],
       ...,
       [-9.38964944e-07,  4.74558154e-07, -5.82215655e-07, ...,
         9.96011559e-01,  4.87761814e-02,  7.46723702e-02],
       [-9.40818377e-07,  4.72015665e-07, -5.80831278e-07, ...,
         9.95855846e-01,  4.84028336e-02,  7.69797714e-02],
       [-9.41783292e-07,  4.73779145e-07, -5.80387270e-07, ...,
        -9.95823087e-01, -4.91143553e-02, -7.69630382e-02]])

In [10]:
from brownian_ot.simulation import ConstantForceSimulation

In [11]:
const_f_sim = ConstantForceSimulation(sphere, sim.timestep,
                                          np.array([0, 0, -2e-12, 0, 0, 0]),
                                          sim.viscosity, sim.kT)


In [12]:
const_f_sim.run(500)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
        -0.00000000e+00, -0.00000000e+00, -0.00000000e+00],
       [-7.81598602e-10,  4.58293200e-09, -6.44832930e-10, ...,
        -7.11968550e-05,  3.84858617e-04, -7.69388550e-05],
       [-1.24328387e-09,  2.80647370e-09, -2.29323395e-09, ...,
        -3.91109306e-04, -1.28337776e-03,  4.39542409e-04],
       ...,
       [-9.01001817e-08, -1.61430677e-08, -4.73192634e-07, ...,
        -2.15925542e-02, -2.13832329e-03,  1.51546483e-02],
       [-8.72135942e-08, -1.49650218e-08, -4.73592202e-07, ...,
        -2.17497264e-02, -2.54997729e-03,  1.53491639e-02],
       [-8.48608581e-08, -1.51013590e-08, -4.73598283e-07, ...,
         2.12864333e-02,  2.49939478e-03, -1.56535684e-02]])

In [13]:
np.array([0, 0, 0, 0, 0, 3e-18])

array([0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 3.e-18])